language: node_js
node_js:
  - "6"

install:
  - yarn install
  - yarn flow-typed install

script:
  - yarn lint
  - yarn flow

deploy:
  on:
    branch: master
  provider: script
  script:
    - yarn deploy
  skip_cleanup: true