language: node_js
node_js:
  - "6"

install:
  - yarn install
  - yarn flow-typed install

script:
  - yarn lint
  - yarn flow

# пока не разобрался, как токен авторизации Now на Travis прокинуть 
#deploy:
#  on:
#    branch: master
#  provider: script
#  script:
#    - yarn deploy
#  skip_cleanup: true